sonar.projectKey=${SONAR_PROJECT_KEY}
sonar.organization=${SONAR_ORGANIZATION}
sonar.host.url=https://sonarcloud.io
sonar.sources=backend/src/main
sonar.tests=backend/src/test
sonar.java.binaries=backend/build/classes/java/main
sonar.coverage.jacoco.xmlReportPaths=backend/build/reports/jacoco/test/jacocoTestReport.xml